### ISSUE TITLE
Error on using Multisvm

### ISSUE THREAD

**Issue by tonystark12** [IPL-UV/altoolbox#1] opened 2015-07-17 15:36 UTC
I get an error in the code when I run the demo.m.

 Adjusting SVM parameters .../bin/bash: ./multisvm: No such file or directory

Error using GridSearch_Train_CV (line 46)
Error running multisvm

Error in AL (line 191)
            options.modelParameters = GridSearch_Train_CV(trnSet, num_of_classes, sigmas,
            Cs, nfolds, rundir);

Error in demo (line 35)
[accCurve.(name) predictions.(name), criterion.(name), sampList.(name),
modelParameters.(name)] = ...

Any idea how to fix this?

**Comment by Jordi-** [comment] 2015-07-17 16:15
You have to compile 'multisvm' and place the binary in the directory where the AL toolbox resides, or use the binary we provide at https://github.com/IPL-UV/altoolbox/releases.

**Comment by tonystark12** [comment] 2015-07-17 16:31
I included the executable from the 'linux_64' folder, from 'binaries' into
my altoolbox folder, before running the code. I have the error inspite of
that

**Comment by tonystark12** [comment] 2015-07-17 16:38
the variable 'rundir' reads something like this

rundir =

./run_SVM_Random

Is this correct?

**Comment by tonystark12** [comment] 2015-07-17 16:51
Any help or direction please.

**Comment by tonystark12** [comment] 2015-07-17 16:57
SVM with random sampling
  Adjusting SVM parameters .../bin/bash: ./multisvm: No such file or directory

Error using GridSearch_Train_CV (line 48)
Error running multisvm

Error in AL (line 191)
            options.modelParameters = GridSearch_Train_CV(trnSet, num_of_classes, sigmas,
            Cs, nfolds, rundir);

Error in demo (line 35)
[accCurve.(name) predictions.(name), criterion.(name), sampList.(name),
modelParameters.(name)] = ...

**Comment by tonystark12** [comment] 2015-07-17 16:57
That is the complete terminal after executing

**Comment by Jordi-** [comment] 2015-07-17 18:10
Maybe it cannot found some needed libraries, or it cannot execute the multisvm binary.
Do a `chmod +x multsivm` to give it execute permission.  If still does not work, try executing `ldd multisvm` and see if there is any missing library in your system.

**Comment by tonystark12** [comment] 2015-07-17 18:17
linux-vdso.so.1 =>  (0x00007fff41400000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007fb6ca890000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb6ca588000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb6ca370000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb6c9fa8000)
/lib64/ld-linux-x86-64.so.2 (0x00007fb6cabd0000)

The above is the result of ldd multisvm.  any idea on how I can use this to
deduce what I want?

**Comment by tonystark12** [comment] 2015-07-17 18:18
Sorry for asking immediately. what I meant is, can you please tell me, how
to find the missing Libraries from the given info. Am slightly new to using
ubuntu, so please bare with me

**Comment by Jordi-** [comment] 2015-07-17 18:21
If any library is missing the result of that command is `not found` for it. It seems that all libraries are in place.
Can you try executing multisvm directly from the command line in the AL directory, e.g., `./multisvm`, and see what happens?

**Comment by tonystark12** [comment] 2015-07-17 18:25
It asks for arguments

**Comment by Jordi-** [comment] 2015-07-17 18:33
That means that multisvm works, but MATLAB cannot find it. Are you sure you are launching 'AL' from MATLAB in the same directory where multisvm is placed? You may try to do a `dir` in the MATLAB command prompt and see if all files are there.

**Comment by tonystark12** [comment] 2015-07-18 01:05
after running the code, and having the error, I run DIR from the matlab
terminal, and I found that the current working directory is different. So I
changed it within the code by adding a lin with 'cd' command. Thank you for
your kind help.

Am aiming to classify satellite images, based on water, vegetation, urban
area, under development, Roads. Can you please tell me how I can use this
toolbox to my benefit?

I have a dataset of my own. how can I create a similar mat file and use
this toolbox? Thanks in advance.

**Comment by tonystark12** [comment] 2015-07-18 04:43
whos -file testAVIRIS.mat
  Name          Size                Bytes  Class     Attributes

  CL        10266x1                 82128  double
  IM        10266x200            16425600  double

This is the data I have from the test mat file. Can you please tell me how
I can interpret this?

**Comment by Jordi-** [comment] 2015-07-22 10:39
Good to hear you have it running.

As for the image classification problem you mention, probably the AL toolbox is not the best tool for you. Of course you can use it to classify your images, but the current implementation is focused to easily compare different AL algorithms. To use it in a practical scenario, you would need to write the code that asks you for the labels that the AL algorithm considers best to improve the classification.

I would suggest you to try first standard supervised classification algorithms such as Support Vector Machines, Neural Networks or Random Forests, where you first train a model using a set of previously labelled samples, and then use that model to classify the whole image. All these methods are already implemented in MATLAB or other computer languages, such as Python or R.

As the problem is solved I'm closing this issue.

**Closed as completed by Jordi-** 2015-07-22 10:39 UTC
